[project]
name = "algorithm-design-task-6"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pyqt6>=6.10.1",
    "tqdm>=4.67.1",
]
